exclude: |
  (?x)(
    ^docs/conf.py|
    ^tests/modelica/|
    ^modelica_builder/modelica_parser/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black-jupyter
  # - repo: local
  #   hooks:
  #     - id: modelica-fmt
  #       name: Modelica Formatter
  #       types: [file]
  #       files: \.(mo|mot)$
  #       entry: poetry run format_modelica_files
  #       language: system
  #       pass_filenames: false
